### ISSUE TITLE
Can LMS inline the lambda (Maybe any function calls )?

### ISSUE THREAD

**Issue by LLLLKKKK** [TiarkRompf/lms-clean#36]
Hi,

I'm diving into LMS to find out if it's suitable for my CodeGen project, starting with the test cases and examples.

The test_lambda_cpp case generates std::function in cpp code, could we make some annotation so that LMS can make it inline ?  The function object construction and the function call can be eliminated.

https://github.com/TiarkRompf/lms-clean/blob/c59d998eb5203942799196f12a25e103679506f6/src/test/scala/lms/core/test_lambda_cpp.scala#L10

https://github.com/TiarkRompf/lms-clean/blob/master/src/out/backend/lambda_01.check.c

Thank you very much !

**Comment by feiwang3311** [comment]
when 
```val f = fun { (arr: Rep[Array[Int]]) =>
          arr(0) = 5
        }
```
is used, it means the user wants a staged function (a function in the generated code). If LMS inlines the function, it goes against the user's intention.

if the user wants the function inlined, then simply don't use the `fun` to lift the function. 

Maybe there are situations that the user wants to generate a staged function and wants the function to be inlined? I am not sure.

**Comment by Kraks** [comment]
Given a function of type `Rep[A => B]`, it is not always possible to inline it at staging time, simply because the function can be unknown at staging time. In some cases, especially if you use LMS's `fun` to convert a function of type `Rep[A] => Rep[B]` to type `Rep[A => B]`, then it is indeed possible to inline that at staging time. But it is not always desirable, as it may lead to code explosion if the function gets applied multiple times.

To do that, essentially you need to override how we handle the `"@"` node (or traverse/rewrite the graph afterward), and inspect if the operator is static (i.e. a known function), in that case you can inline it.

**Comment by LLLLKKKK** [comment]
Thanks !
