### ISSUE TITLE
Using external scala class/function accepts T for Rep[T] ?

### ISSUE THREAD

**Issue by LLLLKKKK** [TiarkRompf/lms-clean#37]
Hi,

In the https://scala-lms.github.io/tutorials/query_staged.html SQL engine tutorial, there's a specialized HashMap implementation which recognizes Rep[T]. Could we reuse the scala.collection.mutable.HashMap with some effect notiations so that we can save the effort to reimplement the HashMap when it's not the performance hotspot ?

 In general, can we use external function (or class) defined T->U for our Rep[T] to produce Rep[U] (automatically transformed to Rep[T] -> Rep[U]) ?

Thanks a lot !

**Comment by feiwang3311** [comment]
If we use `Scala.collection.mutable.HashMap`, the logic of storing and fetching values by keys will not be in the generated code. I don't think that is what we want because we want to have a `hash map` or `hash-map-like-logic` in the generated code.

As to changing a function of `T -> U` to `Rep[T] -> Rep[U]`, you can start by changing the function signature types. It might not directly work, due to other explicit types in the function body that need to be `Rep`ed, or due to the lack of method of some `Rep`ed values. If you check the code in here https://github.com/TiarkRompf/lms-clean/tree/master/src/main/scala/lms/collection, you can see that for each `Rep` type, we need to support a list of methods.
